'use server';

import { createClient } from '@/lib/supabase/server';
import { getCurrentUserFromSession } from '@/lib/auth-bridge';
import { uploadFile } from '@/lib/storage';
import { revalidatePath } from 'next/cache';
import { logError } from '@/lib/logger';
import { canAccessMachine } from '@/lib/rbac';
import { createError, createSuccess, ErrorCodes } from '@/lib/errors';
import { logAuditAction } from './audit';
import { processMachineWithAI } from './ai-ingestion';
import { generateMaintenanceRules, autoGenerateDailyChecklists } from './maintenance';
import { normalizeSerialNumber } from '@/lib/normalization';
import { Machine, User } from '@/types/schema';

export type ActionState = {
    message?: string;
    errors?: Record<string, string[]>;
    success?: boolean;
};

/**
 * Enhanced Create Machine Action (Module 1)
 * - Supports up to 35 PDFs
 * - Integrated AI Auto-Fill
 * - Full Audit Logging
 */
export async function createMachine(
    prevState: ActionState,
    formData: FormData
): Promise<ActionState> {
    console.log('[createMachine] MODULE 1 ACTION CALLED');
    const supabase = createClient();
    const user = await getCurrentUserFromSession();

    if (!user || user.role === 'CLIENT_ADMIN' || user.role === 'TECHNICIAN' || user.role === 'OPERATOR') {
        return { success: false, message: 'Forbidden: Admin access required for machine creation.' };
    }

    // 1. Data Collection (Expanded Schema)
    const rawData = {
        serial_number: normalizeSerialNumber(formData.get('serial_number') as string),
        make: formData.get('make') as string,
        model: formData.get('model') as string,
        year: Number(formData.get('year')) || null,
        current_hours: Number(formData.get('current_hours')) || 0,
        owner_org_id: formData.get('organization_id') as string || user.organization_id,
        // Tech Data
        engine_make: formData.get('engine_make') as string,
        engine_serial: formData.get('engine_serial') as string,
        engine_model: formData.get('engine_model') as string,
        shafts_config: formData.get('shafts_config') as string,
        // Logistics
        po_number: formData.get('po_number') as string,
        notes: formData.get('notes') as string,
    };

    // 2. Multi-PDF Handling (Max 35)
    const manualFiles = formData.getAll('manual') as File[];
    const photoFiles = formData.getAll('photos') as File[];

    if (manualFiles.length > 35) {
        return { success: false, message: 'Maximum 35 documents allowed per machine.' };
    }

    try {
        // A. Storage Uploads
        const documentUploads: string[] = [];
        for (const file of manualFiles) {
            if (file.size > 0 && file.type === 'application/pdf') {
                const url = await uploadFile(file);
                documentUploads.push(url);
            }
        }

        const photoUploads: string[] = [];
        for (const file of photoFiles) {
            if (file.size > 0 && file.type.startsWith('image/')) {
                const url = await uploadFile(file);
                photoUploads.push(url);
            }
        }

        // B. Database Insertion
        const { data: machine, error: machineError } = await supabase.from('machines').insert({
            ...rawData,
            owner_org_id: rawData.owner_org_id || user.organization_id
        }).select('id').single();

        if (machineError) throw machineError;

        const machineId = machine.id;

        // C. Link Documents
        if (documentUploads.length > 0) {
            const docEntries = documentUploads.map((url, i) => ({
                machine_id: machineId,
                organization_id: rawData.owner_org_id,
                title: manualFiles[i].name,
                file_url: url,
                type: 'MANUAL',
                processing_status: 'PROCESSING'
            }));
            await supabase.from('documents').insert(docEntries);
        }

        // D. Link Photos (Simplified as text metadata or separate table)
        // For now, let's assume notes contain photo references or use a generic 'attachments' logic
        if (photoUploads.length > 0) {
            await supabase.from('documents').insert(photoUploads.map((url, i) => ({
                machine_id: machineId,
                organization_id: rawData.owner_org_id,
                title: photoFiles[i].name,
                file_url: url,
                type: 'SERVICE_REPORT' // Placeholder for photos
            })));
        }

        // E. Audit Log
        await logAuditAction({
            action_type: 'CREATE_MACHINE',
            table_name: 'machines',
            record_id: machineId,
            organization_id: rawData.owner_org_id,
            new_data: rawData,
            metadata: { doc_count: documentUploads.length, photo_count: photoUploads.length }
        });

        // F. Trigger AI Ingestion if PDFs uploaded
        if (documentUploads.length > 0) {
            // Async trigger (don't block the main redirect but it's a server action so we might wait a bit or use a worker)
            // For Module 1, we can call it directly to show the result or let it happen in bg
            processMachineWithAI(machineId, documentUploads).catch(console.error);
            
            // NEW: Module 4 Auto-Checklists
            generateMaintenanceRules(machineId).catch(console.error);
            autoGenerateDailyChecklists(machineId).catch(console.error);
        }

        revalidatePath('/dashboard/machines');
        return { success: true, message: 'Machine created with AI ingestion and auto-checklists started.', machineId: machineId } as any;

    } catch (e: any) {
        logError('error.database', e, { action: 'createMachine_v1' });
        return { success: false, message: e.message || 'Failed to create machine.' };
    }
}

/**
 * Upload a Manual for a Machine
 * - Handles PDF upload
 * - Updates 'documents' table
 * - RBAC enforced
 */
export async function uploadMachineManual(
    userId: string,
    machineId: string,
    formData: FormData
) {
    const supabase = createClient();
    const authUser = await getCurrentUserFromSession();

    if (!authUser) {
        return createError(ErrorCodes.UNAUTHORIZED, 'Authentication required');
    }

    // Get user details for RBAC check
    const { data: userRow, error: userError } = await supabase
        .from('users')
        .select('*')
        .eq('id', authUser.id)
        .single();

    if (userError || !userRow) {
        return createError(ErrorCodes.AUTH_ERROR, 'User not found');
    }

    // Force cast to User (snake_case) for RBAC compatibility
    // RBAC expects the database schema shape
    const user = userRow as any as import('@/types/schema').User;
    const organization_id = user.organization_id;

    // RBAC: Check if user can access this machine
    const hasAccess = await canAccessMachine(user, machineId);
    if (!hasAccess) {
        return createError(ErrorCodes.FORBIDDEN, 'Access denied to this machine');
    }

    const file = formData.get('file') as File;
    const title = formData.get('title') as string;

    if (!file || file.size === 0) {
        return createError(ErrorCodes.INVALID_INPUT, 'No file provided');
    }
    if (file.type !== 'application/pdf') {
        return createError(ErrorCodes.INVALID_FILE_TYPE, 'Only PDF files are allowed');
    }

    try {
        // 1. Upload to Storage (validates MIME, magic number, size)
        const fileUrl = await uploadFile(file);

        // 2. Save metadata to DB
        const { data: newDoc, error } = await supabase
            .from('documents')
            .insert({
                machine_id: machineId,
                title: title,
                file_url: fileUrl,
                file_type: file.type,
                file_size_bytes: file.size,
                uploaded_by: authUser.id
            })
            .select('id')
            .single();

        if (error || !newDoc) {
            return createError(ErrorCodes.DB_ERROR, 'Failed to save document metadata');
        }

        // 3. Trigger Async Document Processing (RAG)
        const baseUrl = (typeof process !== 'undefined' ? process.env.NEXT_PUBLIC_SITE_URL : '') || 'http://localhost:3000';
        fetch(`${baseUrl}/api/webhooks/process-document`, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({
                document_id: newDoc.id,
                machine_id: machineId,
                organization_id: organization_id,
                file_url: fileUrl
            })
        }).catch(e => console.error('Failed to trigger webhook', e));

        revalidatePath(`/dashboard/machines/${machineId}`);
        return createSuccess({ fileUrl }, 'Document uploaded successfully');

    } catch (error) {
        console.error('Upload error:', error);
        if (error instanceof Error && error.message.includes(ErrorCodes.INVALID_FILE_TYPE)) {
            return createError(ErrorCodes.INVALID_FILE_TYPE, error.message.split(': ')[1]);
        }
        if (error instanceof Error && error.message.includes(ErrorCodes.FILE_TOO_LARGE)) {
            return createError(ErrorCodes.FILE_TOO_LARGE, error.message.split(': ')[1]);
        }
        return createError(ErrorCodes.UPLOAD_ERROR, 'Upload failed');
    }
}

/**
 * Delete a Machine
 * - Soft delete or Hard delete based on policy (Hard delete for now to keep it simple for contract test)
 * - Removes associated documents
 */
export async function deleteMachine(machineId: string): Promise<ActionState> {
    const supabase = createClient();
    const user = await getCurrentUserFromSession();

    if (!user) {
        return { success: false, message: 'Unauthorized' };
    }

    // RBAC Check
    // Get user with organization_id
    const { data: userRow } = await supabase.from('users').select('*').eq('id', user.id).single();
    if (!userRow) return { success: false, message: 'User not found' };

    // Check machine ownership
    const { data: machine } = await supabase.from('machines').select('*').eq('id', machineId).single();
    if (!machine) return { success: false, message: 'Machine not found' };

    if (machine.owner_org_id !== userRow.organization_id && userRow.role !== 'SUPER_ADMIN') {
        return { success: false, message: 'Forbidden' };
    }

    try {
        // 1. Get associated documents to delete files from storage
        const { data: documents } = await supabase.from('documents').select('file_url').eq('machine_id', machineId);

        // 2. Delete from DB
        const { error } = await supabase.from('machines').delete().eq('id', machineId);
        if (error) throw error;

        // 3. Delete files from storage (Async cleanup, don't block response)
        if (documents && documents.length > 0) {
            Promise.allSettled(documents.map(doc => {
                // Import dynamically to avoid circular dependencies
                return import('@/lib/storage').then(mod => mod.deleteFile(doc.file_url));
            })).catch(err => console.error('Background storage cleanup failed', err));
        }

        revalidatePath('/dashboard/machines');
        return { success: true, message: 'Machine deleted' };

    } catch (e) {
        console.error('Delete machine error:', e);
        return { success: false, message: 'Failed to delete machine' };
    }
}

/**
 * Automate Maintenance Checklists
 * Checks if current hours crossed any maintenance_rules interval that hasn't been performed yet.
 */
export async function triggerMaintenanceAutomation(machineId: string, currentHours: number, organizationId: string) {
    const supabase = createClient();

    // 1. Fetch rules for this machine
    const { data: rules } = await supabase
        .from('maintenance_rules')
        .select('*')
        .eq('machine_id', machineId)
        .eq('is_active', true);

    if (!rules || rules.length === 0) return;

    // 2. See if currentHours >= interval_hours and if we need to generate one
    for (const rule of rules) {
        if (currentHours >= rule.interval_hours) {
            // Check if we already generated a checklist for this exact rule interval recently to avoid duplicates
            // We can check the `checklists` table to see if one exists with the same template_id and machine_id
            // completed after last_performed_at or something similar. 
            // For now, simpler: check if there's any OPEN checklist for this template.
            if (rule.checklist_template_id) {
                const { data: existing } = await supabase
                    .from('checklists')
                    .select('id')
                    .eq('machine_id', machineId)
                    .eq('template_id', rule.checklist_template_id)
                    .neq('status', 'COMPLETED')
                    .limit(1);

                if (!existing || existing.length === 0) {
                    // Generate new checklist
                    console.log(`[MAINTENANCE AUTOMATION] Triggering Checklist for rule ${rule.id} at ${currentHours}H`);

                    // Note: If you want to use the automated 'System' logic, we leave technician_user_id null or assign to a pool.
                    await supabase.from('checklists').insert({
                        organization_id: organizationId,
                        machine_id: machineId,
                        template_id: rule.checklist_template_id,
                        status: 'DRAFT',
                        is_compliant: false
                    });

                    // We also mark rule as "next interval" or update `next_due_at` if it's recurring.
                    // Assuming interval_hours is the target, we could increment it.
                    await supabase.from('maintenance_rules')
                        .update({ interval_hours: rule.interval_hours + rule.interval_hours }) // Simple recursion
                        .eq('id', rule.id);
                }
            }
        }
    }
}

/**
 * Update Machine Hours Manually & Trigger Automation
 */
export async function updateMachineHours(machineId: string, newHours: number): Promise<ActionState> {
    const supabase = createClient();
    const user = await getCurrentUserFromSession();

    if (!user) return { success: false, message: 'Unauthorized' };

    try {
        // 1. Get machine
        const { data: machine } = await supabase.from('machines').select('owner_org_id, current_hours').eq('id', machineId).single();
        if (!machine) return { success: false, message: 'Machine not found' };

        // 2. Update hours
        const { error } = await supabase.from('machines')
            .update({ current_hours: newHours, updated_at: new Date().toISOString() })
            .eq('id', machineId);

        if (error) throw error;

        // 3. Trigger Maintenance Automation
        await triggerMaintenanceAutomation(machineId, newHours, machine.owner_org_id);

        revalidatePath(`/dashboard/machines/${machineId}`);
        return { success: true, message: 'Hours updated successfully' };

    } catch (e) {
        console.error('Update hours error:', e);
        return { success: false, message: 'Failed to update hours' };
    }
}

export async function searchMachines(query: string): Promise<import('@/types/schema').Machine[]> {
    const authUser = await getCurrentUserFromSession();
    const supabase = createClient();

    if (!authUser) return [];

    const { data, error } = await supabase
        .from('machines')
        .select('*')
        .or(`make.ilike.%${query}%,model.ilike.%${query}%,serial_number.ilike.%${query}%`)
        .eq('owner_org_id', authUser.organization_id)
        .limit(10);

    if (error) {
        console.error('[searchMachines Error]', error);
        return [];
    }

    return data as import('@/types/schema').Machine[];
}

export async function getMachines() {
    const authUser = await getCurrentUserFromSession();
    if (!authUser) return [];
    
    const supabase = createClient();
    const { data, error } = await supabase
        .from('machines')
        .select('*')
        .eq('owner_org_id', authUser.organization_id)
        .order('created_at', { ascending: false });

    if (error) {
        console.error('[getMachines] Error:', error);
        return [];
    }

    return data;
}
