'use server';

import { createClient } from '@/lib/supabase/server';
import { getCurrentUserFromSession } from '@/lib/auth-bridge';
import { GoogleGenerativeAI } from '@google/generative-ai';
import { revalidatePath } from 'next/cache';

export async function generateMaintenanceRules(machineId: string) {
    const user = await getCurrentUserFromSession();
    if (!user) return { success: false, error: 'Unauthorized' };

    const supabase = createClient();

    try {
        const { data: machine } = await supabase.from('machines').select('*').eq('id', machineId).single();
        if (!machine) throw new Error('Machine not found');

        const apiKey = (typeof process !== 'undefined' ? process.env.GEMINI_API_KEY : '') || '';
        const genAI = new GoogleGenerativeAI(apiKey);
        const model = genAI.getGenerativeModel({ model: "gemini-1.5-pro", generationConfig: { responseMimeType: "application/json" } });
        
        const prompt = `
            Tu es l'Expert Maintenance EnviroJim. Génère les règles de maintenance standard pour :
            Machine: ${machine.make} ${machine.model}
            
            TACHE :
            Identifie les intervalles de maintenance (ex: 250h, 500h, 1000h) et les actions principales.
            
            JSON STRICT :
            {
              "rules": [
                {
                  "interval_hours": number,
                  "name": "string",
                  "description": "string"
                }
              ]
            }
        `;

        const responseResult = await model.generateContent(prompt);
        const parsed = JSON.parse(responseResult.response.text());

        for (const rule of parsed.rules) {
            await supabase.from('maintenance_rules').insert({
                organization_id: machine.organization_id,
                machine_id: machineId,
                interval_hours: rule.interval_hours,
                name: rule.name,
                is_active: true,
                alert_lead_hours: 150,
                alert_level: 'NORMAL'
            });
        }

        revalidatePath(`/dashboard/machines/${machineId}`);
        return { success: true };
    } catch (e: any) {
        console.error('[generateMaintenanceRules Error]', e);
        return { success: false, error: e.message };
    }
}

export async function autoGenerateDailyChecklists(machineId: string) {
    const user = await getCurrentUserFromSession();
    if (!user) return { success: false, error: 'Unauthorized' };
    const supabase = createClient();

    try {
        const { data: machine } = await supabase.from('machines').select('*').eq('id', machineId).single();
        if (!machine) throw new Error('Machine not found');

        const apiKey = (typeof process !== 'undefined' ? process.env.GEMINI_API_KEY : '') || '';
        const genAI = new GoogleGenerativeAI(apiKey);
        const model = genAI.getGenerativeModel({ model: "gemini-1.5-flash", generationConfig: { responseMimeType: "application/json" } });

        const prompt = `
            Tu es l'Expert Maintenance EnviroJim. Génère une checklist quotidienne (matin et soir) pour :
            Machine: ${machine.make} ${machine.model}
            
            JSON STRICT :
            {
              "morning_items": [ "string" ],
              "evening_items": [ "string" ]
            }
        `;

        const responseResult = await model.generateContent(prompt);
        const parsed = JSON.parse(responseResult.response.text());

        await supabase.from('checklist_templates').insert({
            organization_id: machine.organization_id,
            machine_id: machineId,
            name: `Daily Morning - ${machine.model}`,
            items: parsed.morning_items.map((text: string) => ({ id: crypto.randomUUID(), stepText: text, requiresPhoto: false }))
        });

        await supabase.from('checklist_templates').insert({
            organization_id: machine.organization_id,
            machine_id: machineId,
            name: `Daily Evening - ${machine.model}`,
            items: parsed.evening_items.map((text: string) => ({ id: crypto.randomUUID(), stepText: text, requiresPhoto: false }))
        });

        return { success: true };
    } catch (e: any) {
        console.error('[autoGenerateDailyChecklists Error]', e);
        return { success: false, error: e.message };
    }
}

export async function processVoiceNote(audioUrl: string) {
    const apiKey = (typeof process !== 'undefined' ? process.env.GEMINI_API_KEY : '') || '';
    const genAI = new GoogleGenerativeAI(apiKey);
    const model = genAI.getGenerativeModel({ model: "gemini-1.5-pro" });

    const prompt = `
        Transcris et reformule pour un superviseur : [AUDIO: ${audioUrl}]
    `;

    const result = await model.generateContent(prompt);
    return { 
        transcription: "Transcription brute...",
        formatted_text: result.response.text()
    };
}
