-- FIX PRODUCTION DRIFT
-- Generated by Nuclear Certification Phase

-- 1. Restore Missing Security Function
CREATE OR REPLACE FUNCTION public.is_super_admin()
RETURNS BOOLEAN AS $$
    SELECT EXISTS (SELECT 1 FROM public.users WHERE id = auth.uid() AND role = 'SUPER_ADMIN' AND deleted_at IS NULL);
$$ LANGUAGE sql STABLE SECURITY DEFINER;

-- 2. Restore Missing RLS Policy
-- Drop first to avoid conflict if partially exists
DROP POLICY IF EXISTS "machine_read" ON public.machines;
CREATE POLICY "machine_read" ON public.machines FOR SELECT USING ((organization_id IN (SELECT org_id FROM public.get_auth_org_hierarchy()) OR assigned_partner_id IN (SELECT org_id FROM public.get_auth_org_hierarchy()) OR public.is_admin()) AND deleted_at IS NULL);

-- 3. Restore Missing Audit Triggers
-- Ensure audit function exists
CREATE OR REPLACE FUNCTION public.log_audit()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO public.audit_logs (table_name, record_id, action_type, changed_by, changed_at, old_data, new_data)
    VALUES (TG_TABLE_NAME, COALESCE(NEW.id, OLD.id), TG_OP, auth.uid(), NOW(), 
            CASE WHEN TG_OP = 'INSERT' THEN NULL ELSE row_to_json(OLD)::JSONB END,
            CASE WHEN TG_OP = 'DELETE' THEN NULL ELSE row_to_json(NEW)::JSONB END);
    RETURN NULL;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Re-create triggers
DROP TRIGGER IF EXISTS tr_audit_orgs ON public.organizations;
CREATE TRIGGER tr_audit_orgs AFTER INSERT OR UPDATE OR DELETE ON public.organizations FOR EACH ROW EXECUTE FUNCTION public.log_audit();

DROP TRIGGER IF EXISTS tr_audit_users ON public.users;
CREATE TRIGGER tr_audit_users AFTER INSERT OR UPDATE OR DELETE ON public.users FOR EACH ROW EXECUTE FUNCTION public.log_audit();

DROP TRIGGER IF EXISTS tr_audit_machines ON public.machines;
CREATE TRIGGER tr_audit_machines AFTER INSERT OR UPDATE OR DELETE ON public.machines FOR EACH ROW EXECUTE FUNCTION public.log_audit();

DROP TRIGGER IF EXISTS tr_audit_tickets ON public.tickets;
CREATE TRIGGER tr_audit_tickets AFTER INSERT OR UPDATE OR DELETE ON public.tickets FOR EACH ROW EXECUTE FUNCTION public.log_audit();

DROP TRIGGER IF EXISTS tr_audit_interventions ON public.interventions;
CREATE TRIGGER tr_audit_interventions AFTER INSERT OR UPDATE OR DELETE ON public.interventions FOR EACH ROW EXECUTE FUNCTION public.log_audit();

-- Ensure audit_logs is RLS protected
ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "audit_read" ON public.audit_logs;
CREATE POLICY "audit_read" ON public.audit_logs FOR SELECT USING (public.is_admin());
-- Revoke write access to audit logs if not already
REVOKE UPDATE, DELETE ON public.audit_logs FROM public, authenticated, service_role;
