export const PROMPT_VERSION = 'machine_intelligence_v7';
// Re-export from centralized modelConfig — single source of truth
export { GEMINI_MODEL } from "./modelConfig";

export const INGESTION_STAGES = {
  A_UPLOAD: 'UPLOAD',
  B_INVENTORY: 'INVENTORY',
  C_EXTRACT: 'EXTRACT',
  D_CONSOLIDATE: 'CONSOLIDATE',
  E_GRAPH_BUILD: 'GRAPH_BUILD',
  F_QA_AUDIT: 'QA_AUDIT',
  G_GAP_REPAIR: 'GAP_REPAIR',
  H_FINALIZATION: 'FINALIZATION',
} as const;

export type IngestionStage = typeof INGESTION_STAGES[keyof typeof INGESTION_STAGES];

export const INGESTION_PHASES = [
  INGESTION_STAGES.A_UPLOAD,
  INGESTION_STAGES.B_INVENTORY,
  INGESTION_STAGES.C_EXTRACT,
  INGESTION_STAGES.D_CONSOLIDATE,
  INGESTION_STAGES.E_GRAPH_BUILD,
  INGESTION_STAGES.F_QA_AUDIT,
  INGESTION_STAGES.G_GAP_REPAIR,
  INGESTION_STAGES.H_FINALIZATION,
];
